- name: install desktop environment KDE
  apt:
    pkg:
      - kde-standard
      - kde-plasma-desktop
    state: present 
    install_recommends: yes
  when: linux_desktop == 'kde'

- name: install desktop environment Cinnamon
  apt:
    pkg:
      - cinnamon-core
      - libgl1-mesa-dri 
      - x11-xserver-utils
      - gnome-terminal
      - lightdm
    state: present 
    install_recommends: no
  when: linux_desktop == 'cinnamon'

- name: install desktop environment Gnome
  apt:
    pkg:
      - gnome
    state: present 
    install_recommends: no
  when: linux_desktop == 'gnome'

- name: install desktop environment Mate
  apt:
    pkg:
      - mate-desktop-environment
      - lightdm
    state: present 
    install_recommends: no
  when: linux_desktop == 'mate'

- name: install desktop environment Xfce
  apt:
    pkg:
      - xfce4
      - xfce4-goodies
      - lightdm
    state: present 
    install_recommends: no
  when: linux_desktop == 'xfce'

- name: install Xorg
  apt: 
    pkg:
      - xorg
    state: present